
# Site Settings
locale                   : "en-US"
title                    : "CrossSplit"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Jihye Kim"
description              : ""
url                      : "https://rlawlgul.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "rlawlgul/rlawlgul"
